export const AUTHENTICATE = 'AUTHENTICATE';

export const DEAUTHENTICATE = 'DEAUTHENTICATE';

export const AUTH_ERROR = 'AUTH_ERROR';

// USER INFO

export const SET_USER_INFO = 'SET_USER_INFO';

export const USER_INFO_LOADING = 'USER_INFO_LOADING';

export const USER_INFO_ERROR = 'USER_INFO_ERROR';

// CATEGORIES

export const SET_CATEGORIES = 'SET_CATEGORIES';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';

export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

// TRANSACTIONS

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';

export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';

export const SET_TRANSACTION_START = 'SET_TRANSACTION_START';

export const TRANSACTIONS_HAS_MORE = 'TRANSACTIONS_HAS_MORE';

export const TRANSACTION_LOADING = 'TRANSACTION_LOADING';

export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

// FILTERING/SORTING

export const SORT_BY_DATE = 'SORT_BY_DATE';

export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT';

export const SET_FILTER_CATEGORY = 'SET_FITLER_CATEGORY';

export const SET_START_DATE = 'SET_START_DATE';

export const SET_END_DATE = 'SET_END_DATE';

export const TOGGLE_FILTER_DRAWER = 'TOGGLE_FILTER_DRAWER';
